version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - events-api

  events-api:
    container_name: events-api
    image: excel-platform/events/api
    build:
      context: ./Excel-Events-Backend/.
      dockerfile: Development.Dockerfile
    volumes:
      - /api/obj
      - /api/bin
      - ./Excel-Events-Backend/API/.:/api
    ports:
      - '5000:5000'
    restart: on-failure
    depends_on:
      - events-db

  events-db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ExcelEvents
    volumes:
      - pgdata-events:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata-events:
