version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./staging.nginx.conf:/etc/nginx/conf.d/default.conf
      - ../cert/:/var/www/html
      - ../cert/dhparam/:/etc/ssl/certs/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - events-api

  events-api:
    image: excelmec/events-api:staging
    container_name: events-api
    volumes:
      - ./Excel-Events-Backend/API/Keys/:/api/Keys/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5000:5000'

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ../cert/:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email platform.excelmec@gmail.com --agree-tos --no-eff-email -d staging.events.excelmec.org

volumes:
  certbot-etc:
  certbot-var:
