version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - events-api

  events-api:
    image: excelmec/events-api:staging
    container_name: events-api
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5000:5000'
